### ISSUE TITLE
Incompatibility with Epic Fight

### ISSUE THREAD

**Issue by IljaToropov-TartuUniversity** [DawnOfTimeMC/dotarmorweapons#10]
Minecraft 1.20.1, Forge 47.3.10, Armor of the Ages-forge-1.20.1-1.2.1, epicfight-forge-20.9.4-1.20.1.

When using one armor (for instance, minecraft default diamond armor), then switching it to Armor of Ages armor (for instance, Anubis armor), then switching stand to battle and back (Epic Fight's stands), some of the armor disappears. Most of the time disappears helmet. 
I saw your comment about it being compatible with Epic Fight mod, so I hope you'll check this bug. I get it with Epic Fight and Armor of ages installed only.

**Comment by PierreChag** [comment]
Hello and thank you for the report.

Our mod only adds some armors and models, it's Epic Fight that handles the custom rendering on the armor parts based on its custom player model and animations.
I can't do much about this bug on my side : it's up to Epic Fight's devs to fix it. You should report it on their discord /git repository.

Have a nice evening :)
