### ISSUE TITLE
Armors are not enchantable

### ISSUE THREAD

**Issue by Kikisito** [DawnOfTimeMC/dotarmorweapons#6]
Hi. 

I'm using Armor of the Ages 1.4.1 on Fabric 0.16.0 (MC 1.21) and I tried to enchant an armor, but the enchanting table/anvil does not recognize Armor of the Ages items.

Can this be fixed?

**Comment by PierreChag** [comment]
Hello :)
Thank you for the report. You are right, I forgot to add the new json file that allows armors to be enchanted. The fix will be in the next release !

**Comment by Kikisito** [comment]
Thanks! :)
